type Repo {
  desc: String @unique
  repoUrl: String @unique
  conStyle: String

  # if fontawesome icon is brand or solid
  brand: Boolean
  solid: Boolean
  faI: String

  # this only for twitter & dev contacts
  hashtag: Boolean
  hashtag_name: String
}

type Query {
  allRepos: [Repo]
}
