type Repo {
  projectName: String! @unique
  repoUrl: String! @unique
  conStyle: String
  faI: String

  # this only for twitter & dev contacts
  hashtag: Boolean
  hashtag_name: String
}

type Query {
  allRepos: [Repo!]!
}
